### ISSUE TITLE
Question: Model inversion

### ISSUE THREAD

**Issue by ddjustina** [hectornieto/pypro4sail#1]
I have a fairly basic understanding of RTM, and I did run PROSPECT in the past in a high level matlab script.
I would like to estimate LAI from Sentinel2 images. Do you happen to have any examples applying this inversion, with the input parameters names?

Thanks!

**Comment by hectornieto** [comment]
There is no unique model inversion approach, but many different approaches, from building many simulations for LUTs or regression models, to optimization algorithms.

For numerical optimization algorithms (e.g. [Newton's method](https://en.wikipedia.org/wiki/Newton%27s_method_in_optimization) of [Quasi-Newton methods](https://en.wikipedia.org/wiki/Quasi-Newton_method)), you could use any of the cost functions coded in [cost_functions.py](https://github.com/hectornieto/pypro4sail/blob/master/pypro4sail/cost_functions.py) (or any other you want to use). 

For building a large number of simulations for LUT inversion or regression algorithms you could use [machine_learning_regression.py](https://github.com/hectornieto/pypro4sail/blob/master/pypro4sail/machine_learning_regression.py). Take for instance a look at the [official S2 biophysical ATBD](https://step.esa.int/docs/extra/ATBD_S2ToolBox_V2.1.pdf). This would involve:
1. Building a large database of random input parameters with [build_prosail_database](https://github.com/hectornieto/pypro4sail/blob/bf8e42cef17371b2ff5ecbcbb735442a0ecb9eff/pypro4sail/machine_learning_regression.py#L370)
2. Runing Pro4SAIL for the input database to generated simulated spectra with [simulate_prosail_lut](https://github.com/hectornieto/pypro4sail/blob/bf8e42cef17371b2ff5ecbcbb735442a0ecb9eff/pypro4sail/machine_learning_regression.py#L625)
3. Training ([train_reg](https://github.com/hectornieto/pypro4sail/blob/bf8e42cef17371b2ff5ecbcbb735442a0ecb9eff/pypro4sail/machine_learning_regression.py#L196)) and testing ([test_reg](https://github.com/hectornieto/pypro4sail/blob/bf8e42cef17371b2ff5ecbcbb735442a0ecb9eff/pypro4sail/machine_learning_regression.py#L283)) a regression model from the simulated I/O database produced in steps 1 & 2
